version: '3.8'

services:
  contract-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - API_KEY=sua-chave-secreta
    volumes:
      - .:/app
    command: node server.js